name: nectar_app
description: Nectar - Virtual Cards.
publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts: ^2.5.0
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  google_sign_in: ^7.2.0
  firebase_core: ^4.11.0
  firebase_auth: ^6.1.0
  firebase_database: ^12.1.1
  firebase_ai: ^3.14.1
  image_picker: ^1.2.3
  open_mail: ^1.2.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
