name: nectar_app
description: Nectar - a virtual business card.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0 # GoogleFonts downloads fonts on-demand, reducing app bundle size.
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  firebase_database: ^12.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
