// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOS9-hqrEKj1TxQrDwW4oXCKqeAE3xVc',
    appId: '1:197889035376:android:107e5830508fbceedab8b5',
    messagingSenderId: '197889035376',
    projectId: 'nectarapp-b1390',
    databaseURL: 'https://nectarapp-b1390-default-rtdb.firebaseio.com',
    storageBucket: 'nectarapp-b1390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7M14g7iD4CiZpR-ChGjzNDn9Qm7-f9vM',
    appId: '1:197889035376:ios:b5478b2a52985da0dab8b5',
    messagingSenderId: '197889035376',
    projectId: 'nectarapp-b1390',
    databaseURL: 'https://nectarapp-b1390-default-rtdb.firebaseio.com',
    storageBucket: 'nectarapp-b1390.firebasestorage.app',
    iosClientId: '197889035376-bbg9knaeaf1q0qg8081mu7bk5mbu54nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.nectarApp',
  );
}
